import { InternshipItem } from "@/types";

export const REAL_INTERNSHIPS: Omit<InternshipItem, "id" | "created_at">[] = [
  {
    title: "Information Security Intern",
    organization: "Tech Mahindra Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "West Bengal",
    type: "On-site",
    stipend: 18000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information / Cyber Security",
    description: "Join Tech Mahindra as an Information Security Intern. You will be responsible for assisting in vulnerability assessments, security monitoring, and implementing cybersecurity protocols. Candidates must be available for an in-person internship for 9 months.",
    required_skills: ["Cyber Security", "Network Security", "Risk Assessment"],
    status: "Open",
    openings: 10
  },
  {
    title: "AI and Oracle Cloud Solutions Intern",
    organization: "Tech Mahindra Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Ranga Reddy, Telangana",
    type: "On-site",
    stipend: 25000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Work on cutting-edge AI and Oracle Cloud Digital Engineering solutions. Candidates must possess a B.Tech/B.E in Computer Science & Engineering. This is an in-person opportunity providing hands-on experience in cloud architecture and AI integration.",
    required_skills: ["Artificial Intelligence", "Oracle Cloud", "Cloud Computing"],
    status: "Open",
    openings: 15
  },
  {
    title: "SaaS and Cloud Applications Intern",
    organization: "Tech Mahindra Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Telangana",
    type: "On-site",
    stipend: 22000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Assist the engineering team in developing and deploying Software as a Service (SaaS) and Cloud applications. This role requires foundational knowledge of cloud infrastructure and modern web development.",
    required_skills: ["SaaS", "Cloud Infrastructure", "Software Development"],
    status: "Open",
    openings: 5
  },
  {
    title: "AI enabled Operations Intern",
    organization: "Tech Mahindra Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Tamil Nadu",
    type: "On-site",
    stipend: 15000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Optimize business operations using AI-enabled tools and workflows. Ideal for candidates looking to bridge the gap between artificial intelligence and day-to-day enterprise operations.",
    required_skills: ["Artificial Intelligence", "Operations Management", "Process Optimization"],
    status: "Open",
    openings: 8
  },
  {
    title: "IIoT Intern",
    organization: "Solar Industries India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Maharashtra",
    type: "On-site",
    stipend: 12000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Work with the Industrial Internet of Things (IIoT) team at Solar Industries. You will assist in connecting manufacturing hardware with cloud dashboards for real-time monitoring.",
    required_skills: ["IoT", "Networking", "Hardware Integration"],
    status: "Open",
    openings: 12
  },
  {
    title: "KYC Internship",
    organization: "Capgemini Technology Services India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Uttar Pradesh",
    type: "On-site",
    stipend: 14000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Join Capgemini to assist in IT-enabled Know Your Customer (KYC) compliance operations. This role involves data verification, document processing, and utilizing internal IT tools for compliance.",
    required_skills: ["Data Verification", "Compliance", "IT Operations"],
    status: "Open",
    openings: 20
  },
  {
    title: "Invoice Processing Internship",
    organization: "Capgemini Technology Services India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Tamil Nadu",
    type: "On-site",
    stipend: 16000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Support the finance-IT bridge team by managing automated invoice processing pipelines. Learn to work with enterprise resource planning (ERP) software and resolve processing bottlenecks.",
    required_skills: ["Data Entry", "ERP Software", "Finance Operations"],
    status: "Open",
    openings: 10
  },
  {
    title: "Talent Acquisition Internship",
    organization: "Capgemini Technology Services India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Maharashtra",
    type: "On-site",
    stipend: 20000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Assist the IT Talent Acquisition team in sourcing, screening, and onboarding technical candidates. A great opportunity to learn about technical recruitment in a multinational IT services firm.",
    required_skills: ["Recruitment", "Communication", "HR Operations"],
    status: "Open",
    openings: 5
  },
  {
    title: "Automation Testing Internship",
    organization: "Capgemini Technology Services India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Maharashtra",
    type: "On-site",
    stipend: 24000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Write and execute automated test scripts for enterprise software applications. You will learn modern QA practices and tools to ensure high-quality software delivery.",
    required_skills: ["Software Testing", "Quality Assurance", "Automation Tools"],
    status: "Open",
    openings: 15
  },
  {
    title: "Java Internship",
    organization: "Capgemini Technology Services India Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Maharashtra",
    type: "On-site",
    stipend: 30000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Gain hands-on backend software development experience. You will be writing clean Java code, developing APIs, and participating in agile ceremonies.",
    required_skills: ["Java", "Backend Development", "APIs"],
    status: "Open",
    openings: 25
  },
  {
    title: "PHP Developer Intern",
    organization: "Yesventive IT Labs Pvt Ltd",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Uttar Pradesh",
    type: "On-site",
    stipend: 18000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Develop and maintain dynamic websites and web applications using PHP and MySQL. Assist the core development team in building scalable digital solutions.",
    required_skills: ["PHP", "MySQL", "Web Development"],
    status: "Open",
    openings: 4
  },
  {
    title: "Solution Support Engineer",
    organization: "D-Link (India) Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Delhi",
    type: "On-site",
    stipend: 21000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Provide L1 and L2 technical support for networking solutions. You will be responsible for diagnosing network hardware issues and assisting clients with network configurations.",
    required_skills: ["Networking", "Technical Support", "Troubleshooting"],
    status: "Open",
    openings: 8
  },
  {
    title: "Solution Support Engineer",
    organization: "D-Link (India) Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Goa",
    type: "On-site",
    stipend: 17500,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "Information Technology",
    description: "Join the Goa engineering center to support enterprise networking equipment. Responsibilities include resolving technical tickets and testing network topologies.",
    required_skills: ["Networking", "Hardware Diagnostics", "IT Support"],
    status: "Open",
    openings: 5
  },
  {
    title: "Data and Integration Intern",
    organization: "Persistent Systems Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Maharashtra",
    type: "On-site",
    stipend: 28000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Assist in data engineering pipelines and systems integration. You will work with ETL tools, databases, and APIs to ensure seamless data flow across enterprise platforms.",
    required_skills: ["Data Engineering", "SQL", "APIs", "Integration"],
    status: "Open",
    openings: 10
  },
  {
    title: "AI Intern Hubli",
    organization: "Infosys Limited",
    ministry_or_department: "Prime Minister's Internship Scheme",
    location: "Karnataka",
    type: "On-site",
    stipend: 35000,
    stipend_period: "Monthly",
    duration: "9 Months",
    category: "IT and Software Development",
    description: "Join the AI center of excellence at Infosys Hubli. You will assist in training machine learning models, analyzing datasets, and building AI-driven proofs of concept.",
    required_skills: ["Artificial Intelligence", "Python", "Machine Learning"],
    status: "Open",
    openings: 30
  }
];
